### ISSUE TITLE
There isn't possible to specify a DB host/port

### ISSUE THREAD

**Issue by komw** [tenorok/docker-mongodump#3]
It would be nice to have possibility to provide mongo hostname/port using a environment variables (of course I can rewrite MONGO_PORT_27017_TCP_ADDR but it doesn't looks good)

**Comment by tenorok** [comment]
Hello, @komw I'm agree. I will try to do it in my free time.

**Comment by tenorok** [comment]
As I understand, the point is that `--link` flag is a legacy feature of Docker and it shared environment variables between containers unlike the user-defined networks.

After changes in https://github.com/tenorok/docker-mongodump/pull/4 we can specify host and port explicitly.

**Comment by tenorok** [comment]
Available from [version 1.3](https://hub.docker.com/layers/tenorok/mongodumper/1.3/images/sha256-78b324986e8fb322af353dffc2a88277e8b38406d0b4f58a9529e7dbc0c10525?context=explore).
